INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (1,47,'PSA','Kpg. Moch. Ramdan No. 404, Blitar 77744, DIY');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (2,13,'Sister','Jr. Sukajadi No. 328, Denpasar 50852, KalSel');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (3,30,'Manpro','Ki. Sukajadi No. 775, Jambi 81808, Bengkulu');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (4,26,'Pellentesque.jpeg','Gg. Ikan No. 391, Banjar 56758, Jambi');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (5,38,'PretiumIaculis.tiff','Kpg. Samanhudi No. 741, Administrasi Jakarta Pusat 94547, JaTeng');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (6,25,'PharetraMagnaAc.mp3','Kpg. Raden Saleh No. 296, Bogor 69867, SumUt');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (7,20,'CuraeDonecPharetra.xls','Psr. Sutarjo No. 758, Tangerang 28655, JaTeng');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (8,14,'Amet.tiff','Jr. M.T. Haryono No. 928, Lubuklinggau 44127, JaTeng');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (9,51,'NisiEu.xls','Dk. Rajawali Timur No. 604, Solok 60495, Papua');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (10,62,'LigulaSuspendisse.avi','Gg. Bank Dagang Negara No. 818, Padang 92882, SulTeng');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (11,71,'LuctusEtUltrices.jpeg','Kpg. Jambu No. 11, Mataram 21490, SumUt');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (12,24,'Eu.pdf','Ki. Kiaracondong No. 601, Ternate 80281, SulBar');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (13,55,'CongueDiam.avi','Jr. Tambak No. 742, Jayapura 97845, MalUt');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (14,25,'HabitassePlatea.xls','Jr. Babadan No. 421, Cirebon 68319, KalTeng');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (15,18,'SedTristique.avi','Psr. Sugiono No. 980, Depok 98540, JaTeng');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (16,62,'FusceConsequatNulla.doc','Psr. Bawal No. 187, Bitung 71739, Banten');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (17,58,'MolestieHendreritAt.avi','Gg. Eka No. 276, Tangerang Selatan 64658, JaTim');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (18,58,'DonecQuisOrci.ppt','Dk. Setiabudhi No. 530, Madiun 22977, MalUt');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (19,79,'CommodoVulputate.avi','Gg. R.M. Said No. 451, Serang 78115, NTB');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (20,11,'Ipsum.ppt','Jr. Samanhudi No. 104, Palangka Raya 38747, KalUt');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (21,2,'Platea.jpeg','Dk. Sutarto No. 207, Bandung 46518, NTT');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (22,64,'Donec.gif','Jln. Ir. H. Juanda No. 327, Pontianak 45746, MalUt');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (23,38,'Quis.mp3','Jln. Bak Air No. 706, Langsa 89683, Bali');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (24,68,'Eros.mp3','Psr. Suryo Pranoto No. 288, Pekanbaru 32894, PapBar');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (25,41,'Nibh.doc','Kpg. Sadang Serang No. 628, Madiun 85767, NTB');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (26,11,'Massa.png','Kpg. Babah No. 233, Bitung 87857, Bengkulu');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (27,6,'DuiMaecenasTristique.mov','Kpg. Bass No. 290, Bandar Lampung 61898, Papua');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (28,76,'DuisAliquamConvallis.mp3','Jr. Sumpah Pemuda No. 273, Serang 56496, KalTim');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (29,65,'DiamEratFermentum.ppt','Kpg. Otista No. 983, Sabang 94307, NTB');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (30,11,'MassaVolutpatConvallis.xls','Dk. Banceng Pondok No. 327, Bima 67091, NTB');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (31,48,'NecNisiVolutpat.mp3','Kpg. Moch. Toha No. 279, Kediri 12638, NTT');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (32,17,'RutrumNulla.mpeg','Kpg. Bara Tambar No. 690, Bengkulu 24967, DKI');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (33,27,'EgetErosElementum.jpeg','Dk. Abdul Rahmat No. 642, Salatiga 76604, Banten');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (34,6,'FaucibusOrci.avi','<ul>');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (35,27,'PedeJustoEu.xls','Dk. Villa No. 930, Sorong 70786, DIY');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (36,17,'CongueRisus.mov','Dk. Lumban Tobing No. 603, Makassar 74496, Gorontalo');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (37,73,'Ut.mov','Psr. Yoga No. 312, Surabaya 56316, KalSel');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (38,10,'DapibusDolor.avi','Ki. Laksamana No. 519, Tasikmalaya 26062, DIY');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (39,4,'Lobortis.ppt','Dk. Bata Putih No. 959, Pariaman 46964, JaBar');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (40,4,'OdioElementumEu.mp3','Jr. Bakhita No. 332, Tidore Kepulauan 75012, PapBar');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (41,5,'VestibulumSagittisSapien.doc','Jln. Suryo No. 434, Ambon 23690, KepR');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (42,2,'VestibulumSitAmet.xls','Jr. R.M. Said No. 491, Salatiga 64181, NTB');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (43,13,'Eleifend.png','Ds. Raya Ujungberung No. 929, Makassar 10812, SulTra');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (44,68,'AnteNulla.xls','Dk. Suprapto No. 599, Banjarbaru 11131, KalBar');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (45,55,'TortorQuis.mpeg','Ds. Bagas Pati No. 316, Kediri 67053, KalBar');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (46,56,'ViverraDiam.mp3','Psr. Thamrin No. 297, Kupang 76699, SulTra');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (47,62,'FermentumJusto.ppt','Gg. Agus Salim No. 699, Gunungsitoli 84121, KalUt');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (48,38,'Nulla.tiff','Dk. Jakarta No. 529, Metro 47706, DIY');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (49,30,'EtCommodoVulputate.mp3','Jln. Abdul No. 864, Blitar 39166, KalTeng');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (50,26,'UrnaUtTellus.xls','Jr. Laswi No. 138, Balikpapan 91215, SulBar');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (51,58,'SitAmetEleifend.pdf','263 Maple Wood Pass');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (52,50,'VestibulumSedMagna.xls','1 Village Junction');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (53,18,'NibhInQuis.pdf','251 Westend Plaza');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (54,79,'A.mp3','3 Mayer Pass');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (55,50,'VestibulumAnte.mpeg','29182 Maryland Point');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (56,41,'ImperdietNullamOrci.jpeg','57 2nd Lane');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (57,60,'AugueVestibulum.txt','341 Hallows Point');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (58,51,'SapienIn.xls','2 Delaware Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (59,65,'EuInterdum.mp3','2 Banding Pass');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (60,77,'Urna.ppt','36 Lindbergh Court');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (61,47,'NatoquePenatibus.ppt','437 Clove Lane');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (62,3,'UltriciesEu.xls','07 Clyde Gallagher Street');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (63,45,'FringillaRhoncus.doc','731 International Parkway');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (64,29,'VitaeQuamSuspendisse.mov','41828 Banding Way');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (65,1,'DonecUt.txt','618 Merrick Pass');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (66,54,'Natoque.doc','7 8th Point');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (67,4,'Donec.ppt','58 Claremont Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (68,68,'Eu.ppt','18095 Rockefeller Terrace');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (69,14,'Ultrices.xls','7201 Eggendart Avenue');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (70,58,'Platea.ppt','8622 Elmside Park');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (71,59,'PlaceratPraesent.mov','06800 Forster Junction');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (72,57,'Metus.avi','94 Bunker Hill Point');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (73,21,'VestibulumVestibulumAnte.jpeg','9143 Service Lane');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (74,5,'SitAmetTurpis.mp3','07 Barnett Street');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (75,10,'LobortisLigula.xls','669 Basil Alley');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (76,24,'Lacinia.xls','67 Stone Corner Alley');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (77,54,'MagnaAtNunc.mp3','9974 Bartillon Crossing');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (78,39,'Parturient.avi','58 Parkside Drive');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (79,64,'AmetErosSuspendisse.mp3','67840 Prairieview Lane');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (80,60,'RhoncusSedVestibulum.avi','6696 Valley Edge Center');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (81,76,'TurpisNec.ppt','090 Division Alley');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (82,55,'Sapien.mp3','05116 Cherokee Park');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (83,57,'IntegerAcLeo.mp3','49 Hoard Crossing');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (84,63,'LobortisVelDapibus.tiff','07 Hazelcrest Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (85,25,'Maecenas.xls','7129 Elmside Plaza');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (86,80,'AtNuncCommodo.jpeg','19678 Schlimgen Circle');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (87,17,'NislNunc.txt','4 Golden Leaf Road');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (88,36,'FeugiatNonPretium.tiff','33 Meadow Ridge Point');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (89,47,'LiberoUt.mp3','0959 Elmside Parkway');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (90,68,'Nibh.mov','8 American Alley');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (91,15,'Donec.mpeg','9521 Dayton Lane');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (92,62,'Non.xls','288 Loomis Way');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (93,49,'Dis.ppt','48 Southridge Terrace');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (94,43,'NonVelit.ppt','5756 Hallows Road');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (95,25,'In.avi','58024 Dexter Point');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (96,59,'Imperdiet.xls','7084 Del Sol Pass');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (97,3,'ViverraPedeAc.mpeg','66019 Dennis Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (98,7,'LuctusEtUltrices.ppt','4408 Green Ridge Center');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (99,71,'Adipiscing.jpeg','15 David Point');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (100,3,'Neque.pdf','0260 American Ash Drive');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (101,40,'Aliquam.avi','80397 Prairie Rose Place');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (102,42,'PlateaDictumstMorbi.tiff','02 Express Center');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (103,58,'InHac.mp3','4116 Manitowish Junction');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (104,51,'CurabiturIn.xls','233 Victoria Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (105,78,'TortorQuis.pdf','8420 Ridge Oak Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (106,41,'MattisPulvinarNulla.ppt','6 Morrow Center');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (107,59,'AnteVestibulumAnte.png','603 Birchwood Lane');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (108,80,'TempusSemper.avi','9137 Utah Road');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (109,78,'LobortisEst.tiff','444 Park Meadow Street');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (110,6,'MolestieLoremQuisque.avi','4 Graceland Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (111,76,'VulputateLuctusCum.mov','81 Logan Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (112,10,'RidiculusMus.avi','8 Reinke Court');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (113,62,'SitAmet.mpeg','97 Ohio Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (114,22,'TempusSit.avi','401 Glacier Hill Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (115,30,'FeugiatEt.xls','8138 Sherman Avenue');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (116,38,'Consequat.mp3','8509 Weeping Birch Plaza');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (117,17,'InFelis.xls','43 Delaware Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (118,18,'LectusPellentesque.mov','788 Old Shore Hill');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (119,46,'PortaVolutpatQuam.mpeg','444 Dawn Plaza');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (120,31,'QuisTurpisSed.xls','42 Green Ridge Junction');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (121,65,'RisusPraesent.ppt','79 Ridgeview Circle');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (122,72,'TellusSemperInterdum.avi','6099 Lillian Center');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (123,7,'Dui.mpeg','54 Pearson Park');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (124,56,'LoremIpsumDolor.tiff','18449 Maple Wood Park');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (125,67,'In.ppt','4 East Parkway');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (126,46,'Donec.mp3','04 Rockefeller Place');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (127,71,'MolestieLorem.avi','655 Crowley Terrace');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (128,48,'DonecDiam.mp3','4 Upham Avenue');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (129,66,'LoremId.xls','6 5th Way');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (130,52,'LectusAliquamSit.ppt','7528 Graceland Plaza');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (131,28,'SuspendissePotentiCras.mp3','9864 Northland Center');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (132,63,'InAnteVestibulum.tiff','1 Oak Valley Way');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (133,19,'Pulvinar.mp3','6 Shasta Parkway');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (134,3,'Id.ppt','25 Hagan Trail');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (135,28,'VulputateElementum.mpeg','52084 Bultman Point');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (136,12,'PlaceratPraesent.tiff','28013 Sundown Lane');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (137,36,'ConsequatIn.gif','2 Autumn Leaf Street');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (138,67,'In.xls','18473 Hollow Ridge Court');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (139,12,'MusEtiam.xls','53505 Burrows Pass');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (140,51,'Lectus.ppt','3971 Stuart Point');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (141,66,'Id.xls','45960 Sherman Road');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (142,17,'Nisl.jpeg','9 Fallview Lane');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (143,80,'EtMagnis.mpeg','138 Oxford Way');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (144,78,'IntegerTinciduntAnte.ppt','37 Florence Alley');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (145,72,'CrasMiPede.tiff','0947 Hovde Avenue');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (146,57,'TortorRisusDapibus.mp3','089 Springs Plaza');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (147,25,'PellentesqueVolutpat.txt','296 Dennis Center');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (148,25,'NullaTempusVivamus.avi','1 Sherman Junction');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (149,67,'AnteVivamusTortor.xls','2 Prairie Rose Place');
INSERT INTO BERKAS(IdBerkas,IdMKS,Nama,Alamat) VALUES (150,65,'DignissimVestibulumVestibulum.ppt','401 Stephen Parkway');
