INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (1,1101);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (2,1102);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (3,1103);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (4,1108);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (5,1109);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (6,1201);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (7,1202);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (8,1203);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (9,1204);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (10,1205);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (11,1206);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (12,1207);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (13,1208);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (14,1209);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (15,2320);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (16,2885);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (17,2490);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (18,2798);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (19,1995);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (20,2024);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (21,1647);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (22,2164);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (23,1572);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (24,1998);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (25,2093);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (26,1510);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (27,1766);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (28,2088);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (29,1224);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (30,1264);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (31,1414);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (32,3147);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (33,1337);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (34,2879);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (35,1498);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (36,2058);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (37,2492);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (38,2204);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (39,3054);
INSERT INTO RUANGAN(idRuangan,Namaruangan) VALUES (40,2273);




