INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('900300015','Achmad Fauzi, S.Sos., M.E','afauzi','8v1tDzAvR','afauzi@ui.ac.id','Fakultas Ilmu Sosial dan Politik');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('408050320','Agung Shamsuddin Saragih, S.T., MS.Eng.','agung.sham','yh30eBUDgf','agung.sham@ui.ac.id','Fakultas Teknik');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('150903140','Amelia Hezkasari Day, S.S., M.E.','a.hezkasari','fGXnQWeDW','a.hezkasari@ui.ac.id','Program Vokasi');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('160603039','Arief Syarifuddin Fitrianto, M.Si.','a.syarifuddin','N2wEtEGQSN','a.syarifuddin@ui.ac.id','Fakultas Matematika dan Ilmu Pengetahuan Alam');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('607050201','Athor Subroto, S.E., M.M., M.Sc., Ph.D.','athor.subroto','C5CyCl','athor.subroto@ui.ac.id','Fakultas Ekonomi');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('198704262','Bayu Distiawan Trisedya, S.Kom., M.Kom.','b.distiawan','i18AgXd9X','b.distiawan@ui.ac.id','Fakultas Ilmu Komputer');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('197705022','Dina Chahyati, S.Kom., M.Kom.','dina','Nsug9XEx1A','dina@ui.ac.id','Fakultas Ilmu Komputer');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('197607242','Dr. Achmad Nizar Hidayanto, S.Kom., M.Kom','achmad.nizar','3Nh420LSS4sO','achmad.nizar@ui.ac.id','Fakultas Ilmu Komputer');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('195707231','dr. Asri C. Adisasmita, MPH., M.Phil., Ph.D','adisasa','DysxoR4eI','adisasa@ui.ac.id','Fakultas Kesehatan Masyarakat');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('195208031','dr. Dalima Astrawinata, SpPK(K)., MEpid','dalima.astrawinata','XuWAZsAcO8WE','dalima.astrawinata@ui.ac.id','Fakultas Kedokteran');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('196305181','Dr. drg. Sandra Fikawati, MPH','fikawati','YgRwOb','fikawati@ui.ac.id','Fakultas Kesehatan Masyarakat');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('108050306','dr. Eddy Kartadjukardi, SpKK','eddy.kartadjukardi','QTUvttbvvp','eddy.kartadjukardi@ui.ac.id','Fakultas Kedokteran');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('195802261','Dr., Drs. J.Emmed M. Prijoharjono, M.A., M.Sc','jemmed.p09','0O1h5gn7','jemmed.p09@ui.ac.id','Fakultas Ilmu Sosial dan Politik');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('171303001','Drs. R. Muhammad Sumarno, Apt.','m.sumarno','r8HfEMwSYJ','m.sumarno@ui.ac.id','Fakultas Farmasi');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('197305112','Herlina Permata Sari, S.Sos., M.Crim','herlina109','XYC6zs','herlina109@ui.ac.id','Fakultas Ilmu Sosial dan Politik');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('121203003','Muhammad Hafizhuddin Hilman, M.Kom.','h.hilman','mFJYgcM','h.hilman@ui.ac.id','Fakultas Ilmu Komputer');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('706050100','Munawar Holil, S.S., M.Hum.','munawar.holil','QrQNCGhP','munawar.holil@ui.ac.id','Fakultas Ilmu Pengetahuan Budaya');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('196706252','Petrus Mursanto, Ir, M.Sc.Dr','santo','q6E359zx','santo@ui.ac.id','Fakultas Ilmu Komputer');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('161203016','Wardatul Adawiyah, S.E., MBA.','adawiyah','P2p0LfNEn','adawiyah@ui.ac.id','Fakultas Ekonomi');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('120805038','Wisnu Jatmiko, S.T., M.Kom., Dr. Eng.','wisnu','NAGvrcc','wisnu@ui.ac.id','Fakultas Ilmu Komputer');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('123456789','Phillip Moreno','pmoreno0','qmtc5Rrp','pmoreno0@mtv.com','Eazzy');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('526421871','Harold Price','hprice1','71qejaIl7','hprice1@un.org','Babbleopia');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('919611916','Mary Stephens','mstephens2','kjJzQC16X6','mstephens2@upenn.edu','Ntags');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('369949417','Helen Richardson','hrichardson3','GX5yYL','hrichardson3@google.com','Voomm');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('244149429','Timothy Cox','tcox4','mHNOpk','tcox4@canalblog.com','Jaxnation');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('430897707','Jimmy Stone','jstone5','f3XmZoeHddC','jstone5@mlb.com','Thoughtstorm');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('867608389','Bonnie Reynolds','breynolds6','utCqYWKnv','breynolds6@japanpost.jp','Pixoboo');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('516775665','Kathleen Arnold','karnold7','wUS9QHyu','karnold7@ezinearticles.com','Flipbug');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('776714722','Victor Greene','vgreene8','ZPnWskDTo','vgreene8@salon.com','Blogtags');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('807070894','Peter Hughes','phughes9','3e4pR1LFF','phughes9@dot.gov','Skibox');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('499898086','Brenda Martin','bmartina','fKtGpKhXFWw5','bmartina@linkedin.com','Jabbertype');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('856441879','Melissa Davis','mdavisb','SL6H6oR','mdavisb@cnbc.com','Eazzy');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('581363655','Mary Gutierrez','mgutierrezc','2C5pMezS','mgutierrezc@slashdot.org','Gigashots');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('674241053','Robin Alexander','ralexanderd','2h0LAa2bisK','ralexanderd@clickbank.net','Eare');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('162413295','Phyllis Gomez','pgomeze','QReS4XCc','pgomeze@psu.edu','Edgepulse');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('901691744','Carol Ford','cfordf','gRQN3DD0v','cfordf@hugedomains.com','Tagcat');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('413357936','Jerry Rivera','jriverag','Xpkh8byj','jriverag@wix.com','Photojam');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('262988946','Jessica Dunn','jdunnh','zXv6jW1pGF','jdunnh@newsvine.com','Mynte');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('961486657','Betty Hawkins','bhawkinsi','w8CeOh','bhawkinsi@studiopress.com','Rhynyx');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('440091768','Sharon Fields','sfieldsj','jECCt8','sfieldsj@ask.com','Gabvine');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('735312454','Sara Rose','srosek','aPegf8LfFpO1','srosek@devhub.com','Dabvine');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('666878991','Jeremy Edwards','jedwardsl','Cl5GsZFaPTeA','jedwardsl@prweb.com','Plambee');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('806548500','Eugene Reid','ereidm','a6XRKK6eWc','ereidm@delicious.com','Lajo');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('650709167','Alan Williamson','awilliamsonn','lo8JaKRdjMnb','awilliamsonn@smh.com.au','Yakijo');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('538823615','Chris Mitchell','cmitchello','NsCvQ0au','cmitchello@bing.com','Zava');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('442197832','Helen Owens','howensp','FoFS4dIo4','howensp@hibu.com','Oyoba');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('560512195','Phillip Ruiz','pruizq','LW1wdWKvUX','pruizq@nature.com','Twitterworks');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('184335189','Arthur Ray','arayr','FTHzsmnTumI6','arayr@histats.com','Mudo');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('843400803','Amanda Weaver','aweavers','2v7T1PT1i','aweavers@amazon.co.jp','Oloo');
INSERT INTO DOSEN(NIP,nama,username,password,email,institusi) VALUES ('575339147','Kimberly Olson','kolsont','u2tQHi6xWie','kolsont@bbc.co.uk','Plambee');
