CREATE TABLE MATA_KULIAH_SPESIAL(
   IdMKS  INT  NOT NULL UNIQUE
  ,NPM    CHAR(10) NOT NULL
  ,Tahun  INT  NOT NULL
  ,Semester INT  NOT NULL
  ,Judul  VARCHAR(250) NOT NULL
  ,IsSiapSidang BOOLEAN  NOT NULL
  ,PengumpulanHardCopy BOOLEAN  NOT NULL
  ,IjinMajuSidang BOOLEAN  NOT NULL
  ,IdJenisMKS INT  NOT NULL
  ,PRIMARY KEY (IdMKS, NPM, Tahun, Semester)
  ,FOREIGN KEY (NPM) REFERENCES MAHASISWA(NPM)
  ,FOREIGN KEY (Tahun, Semester) REFERENCES TERM (Tahun, Semester)
  ,FOREIGN KEY (IdJenisMKS) REFERENCES JENISMKS (Id)
);
