CREATE TABLE BERKAS(
  IdJadwal INT NOT NULL
  ,IdMKS  INT  NOT NULL
  ,Tanggal DATE NOT NULL
  ,JamMulai TIME  NOT NULL
  ,JamSemester TIME NOT NULL
  ,IdRuangan INT NOT NULL
  ,PRIMARY KEY (IdJadwal, IdMKS)
  ,FOREIGN KEY (IdMKS) REFERENCES MATA_KULIAH_SPESIAL(IdMKS)
  ,FOREIGN KEY (IdRuangan) REFERENCES RUANGAN (IdRuangan)
);
