INSERT INTO TERM(Tahun,Semester) VALUES (2016,2);
INSERT INTO TERM(Tahun,Semester) VALUES (2016,4);
INSERT INTO TERM(Tahun,Semester) VALUES (2017,3);
INSERT INTO TERM(Tahun,Semester) VALUES (2017,8);
INSERT INTO TERM(Tahun,Semester) VALUES (2017,6);


