CREATE TABLE DOSEN(
   NIP    VARCHAR(20) PRIMARY KEY
  ,nama   VARCHAR(100) NOT NULL
  ,username VARCHAR(50) NOT NULL
  ,password VARCHAR(20) NOT NULL
  ,email  VARCHAR(100) NOT NULL
  ,institusi VARCHAR(100) NOT NULL
);